package:
  name: ceph-csi
  version: "3.14.1"
  epoch: 0
  description: "CSI driver for Ceph"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ceph-libs

environment:
  contents:
    packages:
      - ceph-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ceph/ceph-csi
      tag: v${{package.version}}
      expected-commit: 4d7f8684f093191939bc01bb94b5a0ff43cbcf7b

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/net@v0.38.0
        k8s.io/kubernetes@v1.32.6

  - uses: go/build
    with:
      packages: ./cmd/
      output: cephcsi
      tags: $(awk -F'=' '/^CEPH_VERSION=/ {print $2}' build.env),ceph_preview
      ldflags: -X github.com/ceph/ceph-csi/internal/util.GitCommit=$(git rev-parse HEAD) -X github.com/ceph/ceph-csi/internal/util.DriverVersion=v${{package.version}}

update:
  enabled: true
  github:
    identifier: ceph/ceph-csi
    strip-prefix: v

test:
  pipeline:
    - name: "Verify installation"
      runs: |
        cephcsi --version | grep -F -e "${{package.version}}"
