package:
  name: kafka-4.1
  version: "4.1.1"
  epoch: 0
  description: Apache Kafka is a distributed event streaming platform
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kafka=${{package.full-version}}
    runtime:
      - bash # some helper scripts use bash
      - merged-usrsbin
      - openjdk-${{vars.java-version}}-default-jvm
      - wolfi-baselayout

vars:
  java-version: "21"

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - gradle-8
      - openjdk-${{vars.java-version}}-default-jdk
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/default-jvm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/kafka
      tag: ${{package.version}}
      expected-commit: be816b82d25370ceac697ccf7c88cea873e9b4e3

  - runs: |
      gradle clean releaseTarGz

      tar -xf core/build/distributions/kafka_2.13-${{package.version}}.tgz

      mkdir -p ${{targets.destdir}}/usr/lib/kafka/logs

      mv kafka_2.13-${{package.version}}/bin ${{targets.destdir}}/usr/lib/kafka
      mv kafka_2.13-${{package.version}}/libs ${{targets.destdir}}/usr/lib/kafka
      mv kafka_2.13-${{package.version}}/config ${{targets.destdir}}/usr/lib/kafka

      mv ${{targets.destdir}}/usr/lib/kafka/config/server.properties ${{targets.destdir}}/usr/lib/kafka/config/server.properties.original
      mkdir -p ${{targets.destdir}}/docker-entrypoint-initdb.d/

      # Clean up Windows scripts
      rm -rf ${{targets.destdir}}/usr/lib/kafka/bin/*.bat
      rm -rf ${{targets.destdir}}/usr/lib/kafka/windows

subpackages:
  - name: kafka-iamguarded-compat-${{vars.major-minor-version}}
    description: "compat package with iamguarded/kafka image"
    dependencies:
      provides:
        - kafka-iamguarded-compat=${{package.full-version}}
      runtime:
        - wait-for-port
    pipeline:
      - uses: iamguarded/build-compat
        with:
          package: kafka
          version: ${{vars.major-minor-version}}
      - runs: |
          mkdir -p /opt/iamguarded/kafka/
          ln -s /usr/lib/kafka/bin /opt/iamguarded/kafka/bin
          ln -s /usr/lib/kafka/libs /opt/iamguarded/kafka/libs
          ln -s /usr/lib/kafka/config /opt/iamguarded/kafka/config
          ln -s /usr/lib/kafka/logs /opt/iamguarded/kafka/logs
          ln -sf /opt/iamguarded/scripts/kafka/entrypoint.sh ${{targets.contextdir}}/entrypoint.sh
          ln -sf /opt/iamguarded/scripts/kafka/run.sh ${{targets.contextdir}}/run.sh
      - uses: iamguarded/finalize-compat
        with:
          package: kafka
          version: ${{vars.major-minor-version}}
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - name: "Test compatibility with iamguarded/kafka image"
          runs: |
            test -L /entrypoint.sh
            test -L /run.sh
            test "$(readlink /entrypoint.sh)" = "/opt/iamguarded/scripts/kafka/entrypoint.sh"
            test "$(readlink /run.sh)" = "/opt/iamguarded/scripts/kafka/run.sh"
        - uses: iamguarded/test-compat
          with:
            package: kafka
            version: ${{vars.major-minor-version}}

  - name: kafka-apache-oci-entrypoint-${{vars.major-minor-version}}
    description: "entrypoint scripts and config for apache kafka image"
    dependencies:
      provides:
        - kafka-apache-oci-entrypoint=${{package.full-version}}
      runtime:
        - busybox
        - bash
        - procps
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/opt/kafka
          mkdir -p ${{targets.contextdir}}/var/lib/kafka/data
          mkdir -p ${{targets.contextdir}}/etc/kafka/secrets
          mkdir -p ${{targets.contextdir}}/etc/kafka/docker
          mkdir -p ${{targets.contextdir}}/usr/logs
          mkdir -p ${{targets.contextdir}}/mnt/shared/config
          
          ln -sf /usr/lib/kafka/bin ${{targets.contextdir}}/opt/kafka/bin
          ln -sf /usr/lib/kafka/libs ${{targets.contextdir}}/opt/kafka/libs
          ln -sf /usr/lib/kafka/config ${{targets.contextdir}}/opt/kafka/config

          ./docker/jvm/
          
          # Copy actual Docker scripts from the Kafka repository
          # These scripts are in the docker/ directory of the Kafka source
          if [ -d docker ]; then
            cp -r docker/* ${{targets.contextdir}}/etc/kafka/docker/
            chmod +x ${{targets.contextdir}}/etc/kafka/docker/*
          fi
          
          # Copy default configs to /etc/kafka/docker/
          cp /usr/lib/kafka/config/log4j.properties ${{targets.contextdir}}/etc/kafka/docker/log4j.properties
          cp /usr/lib/kafka/config/tools-log4j.properties ${{targets.contextdir}}/etc/kafka/docker/tools-log4j.properties
          
          # Copy KRaft config if it exists, otherwise use regular server.properties
          if [ -f /usr/lib/kafka/config/kraft/server.properties ]; then
            cp /usr/lib/kafka/config/kraft/server.properties ${{targets.contextdir}}/etc/kafka/docker/server.properties
          else
            cp /usr/lib/kafka/config/server.properties.original ${{targets.contextdir}}/etc/kafka/docker/server.properties
          fi


test:
  environment:
    contents:
      packages:
        - uuidgen
    environment:
      LANG: en_US.UTF-8
      JAVA_HOME: "/usr/lib/jvm/default-jvm"
  pipeline:
    - name: "Initialize Kafka storage"
      runs: |
        export PATH="/usr/lib/kafka/bin:$PATH"

        CLUSTER_ID="$(kafka-storage.sh random-uuid)"
        echo "Using cluster ID: $CLUSTER_ID"

        kafka-storage.sh format -t "$CLUSTER_ID" -c /usr/lib/kafka/config/server.properties.original --standalone
    - runs: |
        export PATH="/usr/lib/kafka/bin:$PATH"

        # Start Kafka
        kafka-server-start.sh /usr/lib/kafka/config/server.properties.original > /dev/null 2>&1 &
        KAFKA_PID=$!
        sleep 5

        TOPIC_NAME="test-topic-$(uuidgen)"
        PARTITIONS=1
        REPLICATION_FACTOR=1

        # Create and verify test topic
        kafka-topics.sh --create --topic "${TOPIC_NAME}" --partitions "${PARTITIONS}" --replication-factor "${REPLICATION_FACTOR}" --if-not-exists --bootstrap-server localhost:9092
        kafka-topics.sh --describe --topic "${TOPIC_NAME}" --bootstrap-server localhost:9092 | grep "${TOPIC_NAME}"

        # Produce a test message
        echo "Hello Kafka" | kafka-console-producer.sh --bootstrap-server localhost:9092 --topic "${TOPIC_NAME}"

        # Consume the message
        consumed_message=$(timeout 10 kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic "${TOPIC_NAME}" --from-beginning --max-messages 1)

        # Verify the message
        if [[ "${consumed_message}" == "Hello Kafka" ]]; then
          echo "Successfully produced and consumed a test message."
        else
          echo "Failed to verify the consumed message."
        fi

        # Clean up the test topic
        kafka-topics.sh --delete --topic "${TOPIC_NAME}" --bootstrap-server localhost:9092

        # Kill Kafka
        kill "${KAFKA_PID}"

update:
  enabled: true
  github:
    identifier: apache/kafka
    tag-filter: 4.1.
    use-tag: true
