package:
  name: thingsboard
  version: 3.7
  epoch: 0
  description: "Open-source IoT Platform - Device management, data collection, processing and visualization."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - dpkg # dpkg requires gnutar and xz
      - gnutar
      - maven
      - nodejs-16
      - openjdk-17
      - openjdk-17-default-jvm
      - xz
      - yarn

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 3528715d2bd5249093ab971bded1fb8b3167210a
      repository: https://github.com/thingsboard/thingsboard.git
      tag: v${{package.version}}

  - runs: |
      mvn clean install -DskipTests -Dlicense.skip=true

subpackages:
  - name: "${{package.name}}-tb-js-executor"
    description: ""
    pipeline:
      - runs: |
          echo "TODO: Build and install tb-js-executor"
    test:
      pipeline:
        - runs: |
            echo "TODO: Test tb-js-executor"

  - name: "${{package.name}}-tb-mqtt-transport"
    description: Thingsboard's transport layer
    dependencies:
      provides:
        - ${{package.name}}-tb-mqtt-transport=${{package.full-version}}
    pipeline:
      - runs: |
          mvn clean install -DskipTests -Dlicense.skip=true
          cd transport/mqtt/target
          dpkg-deb -x *.deb ${{targets.subpkgdir}}
    test:
      pipeline:
        - runs: |
            echo "TODO: Test tb-mqtt-transport"
            exit 1

  - name: "${{package.name}}-tb-node"
    description: ""
    pipeline:
      - runs: |
          echo "TODO: Build and install tb-node"
    test:
      pipeline:
        - runs: |
            echo "TODO: Test tb-node"

  - name: "${{package.name}}-tb-web-ui"
    description: ""
    pipeline:
      - runs: |
          echo "TODO: Build and install tb-web-ui"
    test:
      pipeline:
        - runs: |
            echo "TODO: Test tb-web-ui"

update:
  enabled: true
  github:
    identifier: thingsboard/thingsboard
    tag-filter: v
    strip-prefix: v
