package:
  name: tshark-4.4
  version: "4.4.7"
  epoch: 2
  description: "TShark is a network protocol analyzer to dump and analyze network traffic"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    provides:
      - tshark=${{package.full-version}}
    runtime:
      - ${{package.name}}-libs

environment:
  contents:
    packages:
      - brotli-dev
      - build-base
      - busybox
      - c-ares-dev
      - cmake
      - flex
      - gcc-13 # gcc-14 fails with strange pointer clobbering errors
      - glib-dev
      - libcap-utils
      - libgcrypt-dev
      - libpcap-dev
      - speexdsp-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/wireshark/wireshark
      tag: v${{package.version}}
      expected-commit: 7980339b16307b07ff84f7878e68fde07d71fc8b

  - uses: cmake/configure
    with:
      opts: -DBUILD_wireshark=off

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-libs
    dependencies:
      provides:
        - tshark-libs=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/* "${{targets.subpkgdir}}"/usr/lib
    description: ${{package.name}} libraries
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: editcap
    description: Edit and/or translate the format of capture files
    dependencies:
      runtime:
        - ${{package.name}}-libs
    pipeline:
      - runs: |
          install -Dm755 "${{targets.destdir}}/usr/bin/editcap" "${{targets.contextdir}}/usr/bin/editcap"
    test:
      environment:
        contents:
          packages:
            - tcpdump
            - curl
      pipeline:
        - uses: test/tw/ldd-check
        - name: Verify installation
          runs: |
            editcap --help
            editcap --version
        - name: Download a sample .pcap file
          runs: |
            curl https://raw.githubusercontent.com/wireshark/wireshark/master/test/captures/http-ooo2.pcap -o /tmp/test.pcap
        - name: Verify packet split
          runs: |
            cd /tmp
            no_of_packets=$(tcpdump -r test.pcap | wc -l)
            # splitting each packet into its own file
            editcap -c 1 test.pcap split.pcap
            no_of_files=$(ls -1 split* | wc -l)
            if [[ "$no_of_packets" -ne "$no_of_files" ]]; then
              echo "Error: Number of packets ($no_of_packets) does not match number of files ($no_of_files)."
              exit 1
            fi
            echo "Successfully verified packet split."

        - name: Verify discarding packets
          runs: |
            cd /tmp
            no_of_packets=$(tcpdump -r test.pcap | wc -l)
            # discard the first 3 packets
            editcap test.pcap remaining.pcap 1-3
            expected_packets=$((no_of_packets - 3))
            actual_packets=$(tcpdump -r remaining.pcap | wc -l)
            if [[ "$actual_packets" -ne "$expected_packets" ]]; then
              echo "Error: Expected $expected_packets packets in remaining.pcap, but got $actual_packets."
              exit 1
            fi
            echo "Successfully verified discarding packets."


  - name: tshark-4.4-privileged
    description: tshark with cap_net_raw and cap_net_admin capabilities set for running as nonroot user
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          cp -r ${{targets.destdir}}/* ${{targets.contextdir}}/
          # Allow tshark to run as nonroot user
          setcap cap_net_raw,cap_net_admin=eip "${{targets.contextdir}}/usr/bin/tshark"
          setcap cap_net_raw,cap_net_admin=eip "${{targets.contextdir}}/usr/bin/dumpcap"
    test:
      environment:
        contents:
          packages:
            - libcap-utils
      pipeline:
        - runs: |
            getcap /usr/bin/tshark | cut -d ' ' -f2 | grep -q -E '^cap_net_admin,cap_net_raw=eip$'
            getcap /usr/bin/dumpcap | cut -d ' ' -f2 | grep -q -E '^cap_net_admin,cap_net_raw=eip$'
        - uses: test/tw/ldd-check

update:
  enabled: true
  git:
    strip-prefix: v
    tag-filter-prefix: v4.4.

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - name: dump some packets
      runs: |
        tshark -w /tmp/out.pcap -c 10 host example.com&
        sleep 1; curl -sI http://example.com; sleep 1
        tshark -r /tmp/out.pcap -Y "http" |grep '200 OK'
    - uses: test/tw/ldd-check
